spring:
  datasource:
    druid:
      url: jdbc:mysql:///demo?serverTimezone=UTC
      username: root
      password: hcs19980205

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
    serialization:
      fail-on-empty-beans: false
    property-naming-strategy: SNAKE_CASE

  redis:
    port: 6379
    password: hcs
    host: 192.168.149.130
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      shutdown-timeout: 100  # 关闭超时时间

hibernate:
  naming:
    physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy